#!/usr/bin/env python

Import('env')

sources = [
           'register_types.cpp',
           'AppleAuth.m',
           'GodotAppleId.mm',
           'AppleAuthSerializer.m',
           ]

env.add_source_files(env.modules_sources, sources)
